services:
  db:
    image: mysql:8
    container_name: blog_secure_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
      MYSQL_INITDB_SKIP_TZINFO: 1
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_general_ci
    ports:
      - "4102:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
    image: node:22
    container_name: blog_secure_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "4101:5100"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=blog
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    restart: on-failure

  frontend:
    image: node:22
    container_name: blog_secure_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "4100:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  phpmysql:
    image: phpmyadmin
    container_name: blog_secure_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4103:80"
    depends_on:
      - db

volumes:
  db_data:
  backend_node_modules:
  frontend_node_modules:
